package com.example.utils

data class HsnEntry(val code: String, val description: String)

object HsnLookup {
    private val hsnDatabase: Map<String, HsnEntry> = mapOf(
        "rice" to HsnEntry("1006", "Rice"),
        "wheat" to HsnEntry("1001", "Wheat"),
        "flour" to HsnEntry("1101", "Wheat flour"),
        "atta" to HsnEntry("1101", "Wheat flour"),
        "maida" to HsnEntry("1101", "Refined flour"),
        "sugar" to HsnEntry("1701", "Sugar"),
        "salt" to HsnEntry("2501", "Salt"),
        "oil" to HsnEntry("1511", "Palm oil"),
        "sunflower" to HsnEntry("1512", "Sunflower oil"),
        "mustard" to HsnEntry("1514", "Mustard oil"),
        "milk" to HsnEntry("0401", "Milk"),
        "butter" to HsnEntry("0405", "Butter"),
        "ghee" to HsnEntry("0405", "Ghee"),
        "cheese" to HsnEntry("0406", "Cheese"),
        "paneer" to HsnEntry("0406", "Paneer"),
        "curd" to HsnEntry("0403", "Curd yoghurt"),
        "biscuit" to HsnEntry("1905", "Biscuits"),
        "bread" to HsnEntry("1905", "Bread"),
        "cake" to HsnEntry("1905", "Cake pastry"),
        "noodle" to HsnEntry("1902", "Noodles"),
        "pasta" to HsnEntry("1902", "Pasta"),
        "vermicelli" to HsnEntry("1902", "Vermicelli"),
        "coffee" to HsnEntry("0901", "Coffee"),
        "tea" to HsnEntry("0902", "Tea"),
        "chocolate" to HsnEntry("1806", "Chocolate"),
        "candy" to HsnEntry("1704", "Sugar confectionery"),
        "namkeen" to HsnEntry("2106", "Namkeen snacks"),
        "chips" to HsnEntry("2106", "Potato chips snacks"),
        "pickle" to HsnEntry("2001", "Pickle"),
        "sauce" to HsnEntry("2103", "Sauce"),
        "ketchup" to HsnEntry("2103", "Tomato ketchup"),
        "jam" to HsnEntry("2007", "Jams"),
        "honey" to HsnEntry("0409", "Honey"),
        "dal" to HsnEntry("0713", "Lentils dal"),
        "pulses" to HsnEntry("0713", "Pulses"),
        "spice" to HsnEntry("0910", "Spices"),
        "masala" to HsnEntry("0910", "Mixed masala"),
        "pepper" to HsnEntry("0904", "Pepper"),
        "turmeric" to HsnEntry("0910", "Turmeric"),
        "soap" to HsnEntry("3401", "Soap"),
        "shampoo" to HsnEntry("3305", "Shampoo"),
        "toothpaste" to HsnEntry("3306", "Toothpaste"),
        "toothbrush" to HsnEntry("9603", "Toothbrush"),
        "detergent" to HsnEntry("3402", "Detergent"),
        "perfume" to HsnEntry("3303", "Perfume"),
        "cream" to HsnEntry("3304", "Beauty cream"),
        "lotion" to HsnEntry("3304", "Skin lotion"),
        "powder" to HsnEntry("3304", "Talcum powder"),
        "deo" to HsnEntry("3307", "Deodorant"),
        "medicine" to HsnEntry("3004", "Medicine"),
        "tablet" to HsnEntry("3004", "Tablet medicine"),
        "syrup" to HsnEntry("3004", "Syrup medicine"),
        "capsule" to HsnEntry("3004", "Capsule medicine"),
        "cotton" to HsnEntry("5201", "Cotton"),
        "fabric" to HsnEntry("5208", "Cotton fabric"),
        "cloth" to HsnEntry("5208", "Woven fabric"),
        "shirt" to HsnEntry("6205", "Shirt"),
        "trouser" to HsnEntry("6203", "Trouser"),
        "saree" to HsnEntry("5208", "Saree"),
        "kurta" to HsnEntry("6211", "Kurta"),
        "shoe" to HsnEntry("6403", "Shoes footwear"),
        "sandal" to HsnEntry("6402", "Sandal"),
        "chappal" to HsnEntry("6402", "Chappal"),
        "bag" to HsnEntry("4202", "Bags"),
        "box" to HsnEntry("4819", "Carton box"),
        "bottle" to HsnEntry("3923", "Plastic bottle"),
        "plastic" to HsnEntry("3923", "Plastic articles"),
        "paper" to HsnEntry("4802", "Paper"),
        "notebook" to HsnEntry("4820", "Notebook"),
        "pen" to HsnEntry("9608", "Ball pen"),
        "pencil" to HsnEntry("9609", "Pencil"),
        "book" to HsnEntry("4901", "Printed book"),
        "mobile" to HsnEntry("8517", "Mobile phone"),
        "phone" to HsnEntry("8517", "Telephone"),
        "charger" to HsnEntry("8507", "Battery charger"),
        "earphone" to HsnEntry("8518", "Earphone"),
        "cable" to HsnEntry("8544", "Electric cable"),
        "laptop" to HsnEntry("8471", "Laptop computer"),
        "computer" to HsnEntry("8471", "Computer"),
        "printer" to HsnEntry("8443", "Printer"),
        "fan" to HsnEntry("8414", "Electric fan"),
        "bulb" to HsnEntry("8539", "Electric bulb"),
        "led" to HsnEntry("8539", "LED lamp"),
        "wire" to HsnEntry("8544", "Electric wire"),
        "switch" to HsnEntry("8536", "Electric switch"),
        "battery" to HsnEntry("8506", "Battery"),
        "motor" to HsnEntry("8501", "Electric motor"),
        "pump" to HsnEntry("8413", "Pump"),
        "pipe" to HsnEntry("3917", "Plastic pipe"),
        "cement" to HsnEntry("2523", "Cement"),
        "brick" to HsnEntry("6901", "Brick"),
        "paint" to HsnEntry("3208", "Paint"),
        "furniture" to HsnEntry("9403", "Furniture"),
        "chair" to HsnEntry("9401", "Chair seat"),
        "table" to HsnEntry("9403", "Table furniture"),
        "wood" to HsnEntry("4407", "Sawn wood"),
        "steel" to HsnEntry("7208", "Steel flat rolled"),
        "iron" to HsnEntry("7209", "Iron flat rolled"),
        "aluminium" to HsnEntry("7606", "Aluminium sheets"),
        "tyre" to HsnEntry("4011", "Tyre"),
        "tube" to HsnEntry("4013", "Inner tube"),
        "fertilizer" to HsnEntry("3102", "Fertilizer"),
        "seed" to HsnEntry("1209", "Seeds"),
        "vegetable" to HsnEntry("0709", "Vegetables"),
        "potato" to HsnEntry("0701", "Potato"),
        "onion" to HsnEntry("0703", "Onion"),
        "tomato" to HsnEntry("0702", "Tomato"),
        "fruit" to HsnEntry("0811", "Fruits"),
        "banana" to HsnEntry("0803", "Banana"),
        "mango" to HsnEntry("0804", "Mango"),
        "fish" to HsnEntry("0302", "Fish"),
        "chicken" to HsnEntry("0207", "Chicken poultry"),
        "meat" to HsnEntry("0201", "Meat"),
        "egg" to HsnEntry("0407", "Egg"),
        "pizza" to HsnEntry("1905", "Pizza bread"),
        "carry bag" to HsnEntry("3923", "Carry bag plastic"),
        "glass" to HsnEntry("7013", "Glassware"),
        "ceramic" to HsnEntry("6911", "Ceramic tableware"),
        "mattress" to HsnEntry("9404", "Mattress"),
        "blanket" to HsnEntry("6301", "Blanket"),
        "towel" to HsnEntry("6302", "Towel"),
        "curtain" to HsnEntry("6303", "Curtain"),
        "bicycle" to HsnEntry("8712", "Bicycle"),
        "tractor" to HsnEntry("8701", "Tractor"),
        "gold" to HsnEntry("7108", "Gold"),
        "silver" to HsnEntry("7106", "Silver"),
        "coal" to HsnEntry("2701", "Coal"),
        "petrol" to HsnEntry("2710", "Petrol"),
        "diesel" to HsnEntry("2710", "Diesel"),
        "lpg" to HsnEntry("2711", "LPG gas"),
    )

    fun search(query: String): List<HsnEntry> {
        if (query.length < 3) return emptyList()
        val lower = query.lowercase().trim()
        return hsnDatabase.entries
            .filter { (key, _) -> key.contains(lower) || lower.contains(key) }
            .map { it.value }
            .distinctBy { it.code }
            .take(5)
    }
}
